# name: drone-test
# kind: pipeline
# type: docker

# steps:
# - name: test
#   image: alpine
#   commands:
#   - echo "It worked!"

#-----------------------------------

# kind: pipeline
# type: docker
# name: default

# platform:
#   os: linux
#   arch: amd64

# steps:
# - name: drone-test-2
#   image: alpine
#   commands:
#   - echo hello world! Second test!


# -----------------------------------------

# ERROR : linter: untrusted repositories cannot mount host volumes.


# type: docker
# kind: pipeline
# name: default

# steps:
# - name: test
#   image: docker:dind
#   volumes:
#   - name: dockersock
#     path: /var/run/docker.sock
#   commands:
#   - docker ps -a

# volumes:
# - name: dockersock
#   host:
#     path: /var/run/docker.sock


# ---------------------------------------------

kind: pipeline
type: kubernetes
name: default

steps:
- name: greeting
  image: golang:1.12
  commands:
  - go build
  - go test