# name: drone-test
# kind: pipeline
# type: docker

# steps:
# - name: test
#   image: alpine
#   commands:
#   - echo "It worked!"

#-----------------------------------

kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: drone-test-2
  image: alpine
  commands:
  - echo hello world! Second test!
