# name: drone-test
# kind: pipeline
# type: docker

# steps:
# - name: test
#   image: alpine
#   commands:
#   - echo "It worked!"

#-----------------------------------
kind: pipeline
type: exec
name: default

# platform:
#   os: linux
#   arch: amd64

steps:
- name: drone-test-2
  commands:
  - echo hello world! Second test!