name: drone-test
kind: pipeline
type: docker

# steps:
# - name: test
#   image: alpine
#   commands:
#   - echo "It worked!"
steps:
- name: test
  image: node
  commands:
  - npm install
  - npm test